# --- DATABASE CONFIGURATION ---
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=ramil
spring.datasource.password=ramil1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- SQL INITIALIZATION (GIN Index üçün) ---
# Hibernate c?dv?li yaradandan sonra schema.sql-i i?l?tm?si üçün
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# --- REDIS CONFIGURATION ---
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.docker.compose.enabled=false

app.security.jwt.secret=${JWT_SECRET_KEY}
app.security.jwt.expiration=86400000